USE biblioteca;

CREATE TABLE libros (
    id INT PRIMARY KEY AUTO_INCREMENT,
    titulo VARCHAR(100) NOT NULL,
    autor VARCHAR(50) NOT NULL,
    año_publicacion INT,
    genero VARCHAR(30)
);

INSERT INTO libros (id, titulo, autor, año_publicacion, genero) VALUES
(1, 'Cien años de soledad', 'Gabriel García Márquez', 1967, 'Realismo mágico'),
(2, '1984', 'George Orwell', 1949, 'Distopía'),
(3, 'Orgullo y prejuicio', 'Jane Austen', 1813, 'Romance'),
(4, 'El Principito', 'Antoine de Saint-Exupéry', 1943, 'Fábula'),
(5, 'Don Quijote de la Mancha', 'Miguel de Cervantes', 1605, 'Novela'),
(6, 'Matar a un ruiseñor', 'Harper Lee', 1960, 'Drama'),
(7, 'Ulises', 'James Joyce', 1922, 'Modernista'),
(8, 'El gran Gatsby', 'F. Scott Fitzgerald', 1925, 'Novela'),
(9, 'En busca del tiempo perdido', 'Marcel Proust', 1913, 'Modernista'),
(10, 'Crimen y castigo', 'Fiódor Dostoyevski', 1866, 'Filosófica'),
(11, 'Madame Bovary', 'Gustave Flaubert', 1857, 'Realista'),
(12, 'La Odisea', 'Homero', -800, 'Épica'),
(13, 'La Divina Comedia', 'Dante Alighieri', 1320, 'Épica'),
(14, 'Hamlet', 'William Shakespeare', 1603, 'Tragedia'),
(15, 'La Ilíada', 'Homero', -750, 'Épica'),
(16, 'Los miserables', 'Victor Hugo', 1862, 'Histórica'),
(17, 'Guerra y paz', 'León Tolstói', 1869, 'Histórica'),
(18, 'Lolita', 'Vladimir Nabokov', 1955, 'Controversial'),
(19, 'El retrato de Dorian Gray', 'Oscar Wilde', 1890, 'Gótica'),
(20, 'Las uvas de la ira', 'John Steinbeck', 1939, 'Realista'),
(21, 'El señor de los anillos', 'J.R.R. Tolkien', 1954, 'Fantasía'),
(22, 'El hobbit', 'J.R.R. Tolkien', 1937, 'Fantasía'),
(23, 'Fahrenheit 451', 'Ray Bradbury', 1953, 'Ciencia ficción'),
(24, 'Rebelión en la granja', 'George Orwell', 1945, 'Sátira'),
(25, 'El proceso', 'Franz Kafka', 1925, 'Existencialista'),
(26, 'El extranjero', 'Albert Camus', 1942, 'Existencialista'),
(27, 'Drácula', 'Bram Stoker', 1897, 'Terror'),
(28, 'Frankenstein', 'Mary Shelley', 1818, 'Terror'),
(29, 'Anna Karenina', 'León Tolstói', 1877, 'Realista'),
(30, 'Moby Dick', 'Herman Melville', 1851, 'Aventura'),
(31, 'Los hermanos Karamazov', 'Fiódor Dostoyevski', 1880, 'Filosófica'),
(32, 'El guardián entre el centeno', 'J.D. Salinger', 1951, 'Coming-of-age'),
(33, 'El nombre de la rosa', 'Umberto Eco', 1980, 'Misterio'),
(34, 'El código Da Vinci', 'Dan Brown', 2003, 'Thriller'),
(35, 'Las aventuras de Huckleberry Finn', 'Mark Twain', 1884, 'Aventura'),
(36, 'El alquimista', 'Paulo Coelho', 1988, 'Filosófica'),
(37, 'La sombra del viento', 'Carlos Ruiz Zafón', 2001, 'Misterio'),
(38, 'El perfume', 'Patrick Süskind', 1985, 'Histórica'),
(39, 'La metamorfosis', 'Franz Kafka', 1915, 'Existencialista'),
(40, 'El amor en los tiempos del cólera', 'Gabriel García Márquez', 1985, 'Realismo mágico'),
(41, 'Rayuela', 'Julio Cortázar', 1963, 'Experimental'),
(42, 'Pedro Páramo', 'Juan Rulfo', 1955, 'Realismo mágico'),
(43, 'La casa de los espíritus', 'Isabel Allende', 1982, 'Realismo mágico'),
(44, 'Los detectives salvajes', 'Roberto Bolaño', 1998, 'Contemporánea'),
(45, 'Ficciones', 'Jorge Luis Borges', 1944, 'Cuentos'),
(46, 'La ciudad y los perros', 'Mario Vargas Llosa', 1963, 'Realista'),
(47, 'Crónica de una muerte anunciada', 'Gabriel García Márquez', 1981, 'Novela'),
(48, 'La tregua', 'Mario Benedetti', 1960, 'Romance'),
(49, 'La invención de Morel', 'Adolfo Bioy Casares', 1940, 'Ciencia ficción'),
(50, 'Aura', 'Carlos Fuentes', 1962, 'Fantasía'),
(51, 'La fiesta del chivo', 'Mario Vargas Llosa', 2000, 'Histórica'),
(52, 'El túnel', 'Ernesto Sabato', 1948, 'Psicológica'),
(53, 'Los recuerdos del porvenir', 'Elena Garro', 1963, 'Realismo mágico'),
(54, 'Como agua para chocolate', 'Laura Esquivel', 1989, 'Romance'),
(55, 'Arráncame la vida', 'Ángeles Mastretta', 1985, 'Histórica'),
(56, 'La muerte de Artemio Cruz', 'Carlos Fuentes', 1962, 'Realista'),
(57, 'Noticias del imperio', 'Fernando del Paso', 1987, 'Histórica'),
(58, 'El laberinto de la soledad', 'Octavio Paz', 1950, 'Ensayo'),
(59, 'El llano en llamas', 'Juan Rulfo', 1953, 'Cuentos'),
(60, 'La región más transparente', 'Carlos Fuentes', 1958, 'Realista'),
(61, 'Siddhartha', 'Hermann Hesse', 1922, 'Filosófica'),
(62, 'El lobo estepario', 'Hermann Hesse', 1927, 'Filosófica'),
(63, 'Dune', 'Frank Herbert', 1965, 'Ciencia ficción'),
(64, 'Fundación', 'Isaac Asimov', 1951, 'Ciencia ficción'),
(65, 'Un mundo feliz', 'Aldous Huxley', 1932, 'Distopía'),
(66, 'Neuromante', 'William Gibson', 1984, 'Cyberpunk'),
(67, 'El juego de Ender', 'Orson Scott Card', 1985, 'Ciencia ficción'),
(68, 'Los juegos del hambre', 'Suzanne Collins', 2008, 'Distopía'),
(69, 'Harry Potter y la piedra filosofal', 'J.K. Rowling', 1997, 'Fantasía'),
(70, 'El león, la bruja y el armario', 'C.S. Lewis', 1950, 'Fantasía'),
(71, 'El silmarillion', 'J.R.R. Tolkien', 1977, 'Fantasía'),
(72, 'American Gods', 'Neil Gaiman', 2001, 'Fantasía'),
(73, 'Good Omens', 'Neil Gaiman & Terry Pratchett', 1990, 'Humor'),
(74, 'El hombre ilustrado', 'Ray Bradbury', 1951, 'Ciencia ficción'),
(75, 'El cuento de la criada', 'Margaret Atwood', 1985, 'Distopía'),
(76, 'El psicoanalista', 'John Katzenbach', 2002, 'Thriller'),
(77, 'Misery', 'Stephen King', 1987, 'Terror'),
(78, 'It', 'Stephen King', 1986, 'Terror'),
(79, 'El resplandor', 'Stephen King', 1977, 'Terror'),
(80, 'Cujo', 'Stephen King', 1981, 'Terror'),
(81, 'La torre oscura I', 'Stephen King', 1982, 'Fantasía'),
(82, 'Carrie', 'Stephen King', 1974, 'Terror'),
(83, 'El cementerio de animales', 'Stephen King', 1983, 'Terror'),
(84, 'Los pilares de la Tierra', 'Ken Follett', 1989, 'Histórica'),
(85, 'El nombre del viento', 'Patrick Rothfuss', 2007, 'Fantasía'),
(86, 'Canción de hielo y fuego', 'George R.R. Martin', 1996, 'Fantasía'),
(87, 'Juego de tronos', 'George R.R. Martin', 1996, 'Fantasía'),
(88, 'Choque de reyes', 'George R.R. Martin', 1998, 'Fantasía'),
(89, 'Tormenta de espadas', 'George R.R. Martin', 2000, 'Fantasía'),
(90, 'Festín de cuervos', 'George R.R. Martin', 2005, 'Fantasía'),
(91, 'Danza de dragones', 'George R.R. Martin', 2011, 'Fantasía'),
(92, 'El camino de los reyes', 'Brandon Sanderson', 2010, 'Fantasía'),
(93, 'Palabras radiantes', 'Brandon Sanderson', 2014, 'Fantasía'),
(94, 'Juramentada', 'Brandon Sanderson', 2017, 'Fantasía'),
(95, 'El imperio final', 'Brandon Sanderson', 2006, 'Fantasía'),
(96, 'El pozo de la ascensión', 'Brandon Sanderson', 2007, 'Fantasía'),
(97, 'El héroe de las eras', 'Brandon Sanderson', 2008, 'Fantasía'),
(98, 'Elantris', 'Brandon Sanderson', 2005, 'Fantasía'),
(99, 'El archivo de las tormentas', 'Brandon Sanderson', 2010, 'Fantasía'),
(100, 'Elantris', 'Brandon Sanderson', 2005, 'Fantasía');